# Exclude generated files from coverage
coverage:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/mocks.dart"
    - "**/mocks.mocks.dart"
name: flutter_serper
description: A Dart package that provides a strongly-typed wrapper for the Serper API.
version: 1.3.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dotenv: ^4.2.0
  meta: ^1.17.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  custom_lint: ^0.7.5
  freezed_lint: ^0.0.9
