name: flutter_serper
description: A Dart package that provides a simple wrapper for the Serper API.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  dio: ^5.8.0+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
