name: Release Notes

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get Changelog Entry
        id: changelog_entry
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          CHANGELOG_ENTRY=$(awk "/## $VERSION/,/## [0-9]+\.[0-9]+\.[0-9]+/" CHANGELOG.md | sed '/## [0-9]\+\.[0-9]\+\.[0-9]\+$/d')
          echo "CHANGELOG_ENTRY<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_ENTRY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog_entry.outputs.CHANGELOG_ENTRY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
